// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 53);
    lv_obj_set_height(ui_Button1, 26);
    lv_obj_set_x(ui_Button1, 45);
    lv_obj_set_y(ui_Button1, -74);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc4 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Arc4, 86);
    lv_obj_set_height(ui_Arc4, 88);
    lv_obj_set_x(ui_Arc4, -56);
    lv_obj_set_y(ui_Arc4, -44);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 50);


    ui_Dropdown1 = lv_dropdown_create(ui_Screen2);
    lv_obj_set_width(ui_Dropdown1, 94);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 50);
    lv_obj_set_y(ui_Dropdown1, -18);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Slider1 = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 4);
    lv_obj_set_y(ui_Slider1, 22);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Spinner1 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 57);
    lv_obj_set_height(ui_Spinner1, 36);
    lv_obj_set_x(ui_Spinner1, -31);
    lv_obj_set_y(ui_Spinner1, 67);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 37);
    lv_obj_set_height(ui_Spinner2, 36);
    lv_obj_set_x(ui_Spinner2, 22);
    lv_obj_set_y(ui_Spinner2, 69);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags



}
